### ISSUE TITLE
Formula fails if crmsh installation fails in cloud_detection.sls

### ISSUE THREAD

**Issue by arbulu89** [SUSE/habootstrap-formula#57]
The whole formula usage depends on `crmsh`. In fact, the first thing done in the formula is to install `crmsh. But it's not done using the standard way. Here the piece of code:
https://github.com/SUSE/habootstrap-formula/blob/master/cluster/cloud_detection.sls#L2

If this installation fails, the whole formula will fail, as it cannot find the used cloud provider.

Even though this error is rare, we need to fix it or at least have a backup plan.

**Comment by MalloZup** [comment]
@arbulu89  I see but the fix you proposed on `cloud_grains` is doing an http request , that is also a point of failure.

Furthemore, I'm thinking that if the `crmsh` install fail, the whole formula here should be fail since it constructed over `crmsh`.

**Comment by arbulu89** [comment]
@MalloZup We will always have points of error. The issue is that this one (`crmsh` installation was one that happened). I don't think we need to retry all the executions, only the ones that fail. The installation fails because for some reason, our SUSE SCC channels tend to fail time to time. I have not found the same behaviour in the other http calls.

And yes, we could set a `failhard` to the crmsh installation. But this will come in a future change XD
