### ISSUE TITLE
Rename Cluster to HA Cluster

### ISSUE THREAD

**Issue by MalloZup** [SUSE/habootstrap-formula#61]
![image](https://user-images.githubusercontent.com/10886597/95510938-03a8ee80-09b7-11eb-863a-09f45c6ea441.png)

@Simranpal @arbulu89  I think `HA CLUSTER` is better then a `cluster` group

**Comment by MalloZup** [comment]
![image](https://user-images.githubusercontent.com/10886597/95511078-3eab2200-09b7-11eb-84bd-105b61a4c8f1.png)

something in this direction

**Comment by arbulu89** [comment]
> ![image](https://user-images.githubusercontent.com/10886597/95511078-3eab2200-09b7-11eb-84bd-105b61a4c8f1.png)
> 
> something in this direction

Actually, it would make sense to have it in the `Clustering` entry you have just above (where `Caasp` things are available), and change the name to `HA Cluster`

**Comment by MalloZup** [comment]
done
